server:
  port: 8090

spring:
  application:
    name: msvc-student
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka