server:
  port: 8091

spring:
  application:
    name: msvc-course
  datasource:
    url: jdbc:postgresql://localhost:5432/courses
    username: postgres
    password: postgresql
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
